version: 1.1.{build}
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release csMACnz.FluentJsonBuilder.sln /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION

    dotnet test -c Release .\test\csMACnz.FluentJsonBuilder.Tests\csMACnz.FluentJsonBuilder.Tests.csproj

    dotnet pack -c Release -o ${pwd} .\src\csMACnz.FluentJsonBuilder\csMACnz.FluentJsonBuilder.csproj /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION
test: off
artifacts:
- path: csMACnz.FluentJsonBuilder.*.nupkg
  name: nuget
